version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: 5433
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./auth/postgresql/schemas/info.sql:/docker-entrypoint-initdb.d/info.sql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_admin -d auth_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5433
      DB_NAME: auth_db
      DB_USER: auth_admin
      DB_PASSWORD: admin
    ports:
      - "8003:5000"
    depends_on:
      - postgres
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8002:5000"

volumes:
  pgdata:
